#485- Allow non-integer spacing in special register layouts
pasqal-io/Pulser pull request #486
Opened 2023-03-25 15:27 UTC by kvaithin

Fixes #485 

Allow non-integer spacing in special register layouts

2023-03-27 09:01 UTC, HGSilveri requested changes
Hi @kvaithin , thank you for your contribution! 
The changes to the source code look good, all you are missing are some updates to the unit tests and the tutorials.

2023-03-28 08:07 UTC, HGSilveri commented
Hey @kvaithin ! Do you think you'll be able to take care of the necessary changes soon? I can also take care of the rest for you if you prefer it. We want to make a new release by the end of the month and it would be nice to have this merged by then.

2023-03-30 10:11 UTC, HGSilveri approved these changes

2023-03-30 10:14 UTC, merged

2023-03-30 18:35 UTC, kvaithin commented
> Sorry @kvaithin , I had to go ahead and do the remaining changes for you, I hope you don't mind. Thank you very much for your contribution!

Np, thank you. :)